---
title: "Mapping - Sandy Spring, GA"
author: Scott Reeves
# date: 2018-05-20
output: 
  html_document: 
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
set.seed(1014)
#options(digits = 3)

knitr::opts_chunk$set(comment = "#>",collapse = TRUE,cache = TRUE, fig.path = "images/",out.width = "70%",fig.align = 'center',fig.width = 7,fig.asp = 0.618)

options(dplyr.print_min = 5, dplyr.print_max = 5)
```

# Sources and References

__Open Data, City of Sandy Springs__

https://data-coss.opendata.arcgis.com/ 

__Inspiration__

https://xvrdm.github.io/2017/09/15/create-maps-from-sitg-files-with-sf-and-ggplot2/ 

__ggplot2__

http://ggplot2.tidyverse.org/reference/ggsf.html 

__Colors__

http://sape.inf.usi.ch/quick-reference/ggplot2/colour

# Libraries

```{r message=FALSE, warning=FALSE}

library(sf)
library(tidyverse)


# could not find function “geom_sf”
# 
# While running R as the administrator, reinstall ggplot2 like this:
# 
# devtools::install_github("tidyverse/ggplot2")
# require(ggplot2)

library(ggplot2)

# library(tmap)
# library(tmaptools)
# library(rio)
```

## Data

```{r}
# Assign file paths to vars

citylimits <- st_read("F:/datasets/sandyspringsga/City_Limit__Sandy_Springs_Georgia/City_Limit__Sandy_Springs_Georgia.shp")

streets <- st_read("F:/datasets/sandyspringsga/Streets__Sandy_Springs_Georgia/Streets__Sandy_Springs_Georgia.shp")

streets_filt <- st_read("F:/datasets/sandyspringsga/Streets__Sandy_Springs_Georgia__Filtered/Streets__Sandy_Springs_Georgia.shp")

crime <- read.csv("F:/datasets/sandyspringsga/Sandy_Springs_Police_Department.csv")

```

```{r eval=FALSE, include=FALSE}
plot(citylimits[9])
```

```{r}
glimpse(citylimits)
```


```{r eval=FALSE}
# Create a plot

ggplot() +
  
  # add a layer with lightgrey citylimit polygons
  
  geom_sf(data=citylimits, fill="cornflowerblue", color="blueviolet") +
  
  # add a title
  
  labs(title = "Sandy Springs, GA")
  
```

```{r eval=FALSE}
glimpse(streets)

```

```{r eval=FALSE}
ggplot() +
  geom_sf(data = streets_filt %>% filter(StreetType %in% c("RD", "HWY")))
```

```{r}
levels(streets$StreetType)
```


```{r eval=FALSE}
# Create a plot

ggplot() +
  
  # add a layer with lightgrey citylimit polygons
  
  geom_sf(data=citylimits, fill="snow2", color="blueviolet") +
  geom_sf(data = streets %>% filter(ZipCodeLef == "30342" | ZipCodeRig =="30342")) +
  
  # add a title
  
  labs(title = "Sandy Springs, GA")
  
```

```{r eval=FALSE}
glimpse(crime)
```


```{r}
crimedate <- as.Date(crime$incident_datetime, format = "%m/%d/%Y")
```

```{r}
maycrime <- filter(crime, as.Date(incident_datetime, format = "%m/%d/%Y") > "2018-04-30")

head(maycrime)
```

```{r}
maycrime_sf <- st_as_sf(x = maycrime,
                        coords = c("longitude", "latitude"),
                        crs = "+proj=longlat +datum=WGS84")
```

```{r eval=FALSE}
plot(maycrime_sf)
```


```{r}
ggplot() +
  geom_sf(data = citylimits) +
  geom_sf(data = streets_filt %>% filter(StreetType %in% c("RD", "HWY"))) +
  geom_sf(data = maycrime_sf, aes(color = parent_incident_type)) +
  labs(title = "Crime - Sandy Springs, GA - 5/1 thru 5/20/18")


```



```{r}
levels(maycrime$parent_incident_type)
```


# --------------------------


```{r eval=FALSE}
# Assign shapefile to a variable using tmaptools's read_shape()
# as.sf = TRUE means as a simple features object (sf package) akin to a regualr dataframe.

ssgeo <- read_shape(districtsshapefile, as.sf = TRUE)

```

```{r eval=FALSE}
# Try a couple of quick basic plots

plot(ssgeo)
```

```{r eval=FALSE}
qtm(ssgeo)
```

```{r eval=FALSE}
qtm(ssgeo, fill = "DISTRICT")
```


```{r eval=FALSE}
# Assign data file to var
sscrime <- rio::import(crimedatafile)
```

```{r eval=FALSE}
#  View the shapefile structure
str(ssgeo)
```

```{r eval=FALSE}
# View datafile structure
str(sscrime)
```

```{r eval=FALSE}
# Subset the crime data
sscrime2018 <- dplyr::filter(sscrime, incident_datetime > "2017-12-31")
```

```{r eval=FALSE}
tm_shape(ssgeo) +
tm_dots(sscrime2018)

```

```{r eval=FALSE}
map1 + tm_pol
```

