---
title: "Mapping - United States"
author: Scott Reeves
# date: 2018-05-20
output: 
  html_document 
    # toc: true
    # toc_float: true
---

```{r setup, include=FALSE}
set.seed(1014)
#options(digits = 3)

knitr::opts_chunk$set(comment = "#>",collapse = TRUE,cache = TRUE, fig.path = "images/",out.width = "100%",fig.align = 'center',fig.width = 10,fig.asp = 0.618)

options(dplyr.print_min = 5, dplyr.print_max = 5)
```

# Sources and References


[Shapefiles - States](https://www.census.gov/geo/maps-data/data/cbf/cbf_state.html)

[About creating tmap insets for AK and HI](https://github.com/mtennekes/tmap/tree/master/demo/USChoropleth)

[Leaflet Providers](http://leaflet-extras.github.io/leaflet-providers/preview/)



# Libraries

```{r message=FALSE, warning=FALSE}

library(sf)
library(tidyverse)
library(stringr)
library(leaflet)

# While running R as the administrator, reinstall ggplot2 like this:
# 
# devtools::install_github("tidyverse/ggplot2")
# require(ggplot2)

library(ggplot2)
library(tmap)
library(tmaptools)

```

## Data

```{r}


states <- st_read("F:/datasets/uscensus/cb_2017_us_state_5m/cb_2017_us_state_5m.shp")

zipcodes <- st_read("F:/datasets/uscensus/cb_2017_us_zcta510_500k/cb_2017_us_zcta510_500k.shp", stringsAsFactors = FALSE)

```

```{r eval=FALSE}
glimpse(states)
```

```{r eval=FALSE}
levels(states$NAME)
```

```{r}
outside48 <- c("Alaska", "Hawaii", "Puerto Rico", "American Samoa", "United States Virgin Islands", "Guam", "Commonwealth of the Northern Mariana Islands")

contig48dc <- filter(states, !(NAME %in% outside48))
```

```{r}
qtm(contig48dc)
```

```{r message=FALSE, warning=FALSE}

tmap_mode(mode = "plot")

tm_shape(contig48dc) +
  tm_polygons(col = "MAP_COLORS")

```

```{r message=FALSE}
tmap_mode(mode = "view")
tm_shape(contig48dc) + tm_polygons(alpha = 0) + 
  tm_shape(zipcodes303s) + tm_polygons(alpha = .5) + 
  tm_view(basemaps = 'Esri.NatGeoWorldMap')

```


```{r eval=FALSE}
glimpse(zipcodes)
```

```{r}

# value = TRUE is necessary to pull the values rather than the item's vector position

zips303s <- grep("^303", zipcodes$ZCTA5CE10, value = TRUE)

# this also works
# zipcodes303s <- zipcodes %>% filter(ZCTA5CE10 >= "30300" & ZCTA5CE10 <= "30399")

zipcodes303s <- zipcodes %>% filter(ZCTA5CE10 %in% zips303s)

```

```{r}
qtm(zipcodes303s)
```


```{r}

# # WORK on this error:
# 
# # sf layer has inconsistent datum (+proj=longlat +datum=NAD83 +no_defs).
# # Need '+proj=longlat +datum=WGS84'

leaflet(zipcodes303s) %>% 
  addTiles() %>% 
  addPolygons()


```

```{r}
#  The first element to start with is tm_shape, which specifies the shape object. 

# Next, one, or a combination of the following drawing layers should be specified: 
# 
# Base layers
# 
# tm_polygons	    Draw polygons	col
# tm_symbols	    Draws symbols	size, col, shape
# tm_lines	      Draws polylines	col, lwd
# tm_raster	      Draws a raster	col
# tm_text	        Add text labels	text, size, col
# 
# Derived layers
# 
# tm_fill	Fills the polygons	see tm_polygons
# tm_borders	Draws polygon borders	none
# tm_bubbles	Draws bubbles	see tm_symbols
# tm_squares	Draws squares	see tm_symbols
# tm_dots	Draws dots	see tm_symbols
# tm_markers	Draws markers	see tm_symbols and tm_text
# tm_iso	Draws iso/contour lines	see tm_lines and tm_text


```

